# Generated by Django 5.1.1 on 2024-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_available_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_tickets_sold',
            field=models.IntegerField(default=0),
        ),
    ]
